### ISSUE TITLE
Design Task

### ISSUE THREAD

**Issue by maosugaya** [sentogurashi/template#1]
# テンプレ

index : top
about : about
page : 〇〇銭湯
list : 記事一覧
single : 記事

# Task

## Graphic

- [ ] Logo revise
  - [ ]  微調整
  - [ ]  icon決定

- [ ] Social image
  - [ ]  avatar
  - [ ]  tw-cover fix
  - [ ]  fb-cover fix
  - [ ]  og-img fix

## Photo

- [ ]  現像
  - [ ]  fes
  - [ ]  member's shoot 5/14
  - [ ]  member's shoot 5/21

## Web

- [ ]  参考漁る

- [ ]  コンテンツに収める写真のカタを決める(どこにどんな種類のカットが入るなど)
  - [ ]  index
  - [ ]  about
  - [ ]  page

- [ ]  デザインを詰める
  - [ ]  index
  - [ ]  about
  - [ ]  page
  - [ ]  list
  - [ ]  single

**Comment by maosugaya** [comment]
# 5/30 Open

- 唄う : えもちゃん
- 築く : 加糖さん = 部屋をリノベしてる
- 描く : 塩谷さん = 絵を描いてる
- 写す : まお = 写真を撮ってる
- 造る : 大黒さん = 
- 泊まる : みほさん = 部屋の前
- 編む : せおちゃん = 物を描いてる
- 伝える : みやさん = 打ち合わせ
- 興す : なおきさん = 書類もってる
